### ISSUE TITLE
qolor 0.4.1 package is not working anymore

### ISSUE THREAD

**Issue by anilvarmaus** [DavidLGoldberg/qolor#26] opened 2017-02-14 02:03 UTC
The toggle does not have any effect either. It is not working in sql files.

**Comment by DavidLGoldberg** [comment] 2017-02-14 05:10
I cannot reproduce any issue.  I see all of the colors fine on my mac, and all of the tests are passing on the newest and beta Atom.

Just to confirm, your title says "anymore".  You've had it working before?

Try doing cntrl+shift+l (on a mac) or switch language to sql (to make sure the "grammar" is SQL).

If that doesn't work, try doing ctrl+alt+comand + l (L as in load, as in reload, which is a way to restart Atom any time).

Please let me know your system specs and Atom version.

**Comment by ghost** [comment] 2017-03-16 10:27
Hi,
I installed latest 0.4.1 too and have the newest Atom version. But when I would open a ~11MB mysql-file, with Create database tags etc., then the atom editor runs in the message "Editor is not responding".
I use Windows 10 with the newest Updates. Atom editor is 64bit Version. I could not open sql-files when qolor plugin is activated.

**Comment by DavidLGoldberg** [comment] 2017-03-16 15:34
Hmm, you tried the same file without qolor installed and it was fine? Up until relatively recently the 11mb would have just crashed Atom no matter what was installed.

**Comment by DavidLGoldberg** [comment] 2017-03-16 15:46
Closing this issue and making a new one about large files.  I'm sure the 11mb issue has existed for some time and not due to versioning.

**Closed as completed by DavidLGoldberg** 2017-03-16 15:46 UTC

**Comment by anilvarmaus** [comment] 2017-03-26 19:29
Sorry for the trouble David. I figured out what I was doing wrong.


Thank you for keeping me posted.


Best,

Anil

________________________________

**Comment by DavidLGoldberg** [comment] 2017-03-27 13:01
No worries! Let me know what you think / any ideas!  There is a gitter page too (linked on the top of the homepage)
